server:
  port: 9092

#mybatis配置
mybatis:
  type-aliases-package: com.street.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




#spring配置
spring:
  application:
    name: SpringCloud-Provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.185.226:3306/talent-ecosystem?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: JX210111
    password: 123456
  servlet:
    multipart:
      # 启用
      enabled: true
      # 上传文件单个限制
      max-file-size: 5MB
      # 总限制
      max-request-size: 6MB

#alipayconfig:
#  # 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
#  app_id : "2021000117694633"
#  # 商户私钥，您的PKCS8格式RSA2私钥
#  merchant_private_key : "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCUT7XWsdyI8JVTHJTJnvjRRed5Y9CqCUWvtygtZzbQBqV90t1/v2QiqvAzxgNR5uZNrurdmCLM4aAaQpTAOtyVICzwof62ZHCVqJCLoYVkDq34Afk+U5DHstEM9KvpYraZBnZ3Z9wFQLAdyN1+yBVblrLvq7hTBbRPjY3JhYxI5n5qqPgadnbqmsmEiKiWUy97NTUQVuXGr/Ao927iPh5NfFCKTFlC1jMD9eqlcM7lqfAQUpH1WgocKR67gKvB9O+SFwKzH9FiOytnf+sYWVflqg7vRcwvN2ZeaT/a8+bfJGA0n6iRfWEn/+wAO27t8ql5k4hzHO8j4of9HDb3DJWZAgMBAAECggEAJrhgyvqIjx/wfFBb7/+XClvrwN90XNAq52M0FBZ8UvdJQX5J4c5AAGUMbRfnSfy0Z9eg7dWIUGEfgXuchktXx38s/G3uqAO0+P2XLz0uLB9BABzTy5fZlqlytqUyNK5W6cCsMSRmZuCqmjwUx8LJAK5pbPUyHErC9noIaHJ7W5Sb7vGMl1J7ecL+9JeEPDgCuAejAPlhAPBRvOw7qDKCIdx1YEuTpMFrBB279Cciy2rivj8esbzfQ6Qzj4gjtyodtrPq8MDnP0pfomOziqgAw5pCGXXeEby2h2ioy3JmIL/+onqc+xUmlyJamk7W9M0URbTlxrn4mgPK2Xq6uhBPmQKBgQDF9JtkpQvv/G5yfwy+MkQQCIsASy3wFXg939z8sFBdK0id0j2HIQeTSBgyog+O91UzUtuplwczAebciBIxXY0XqEooMTsM1aPeL3r+zojvnw4OTtMY0Iv8Y0XFXAF6O7L4UVO5xzPg+cYBsm/G1jexqqKrOXxIPjRvRiI0CVADMwKBgQC/zJnd5YZ+fPas6Nb2Rk+YVyEjfq7mZXXHVV9h4UfwxGGc7Ep9gIAyTwVtS2ut1Wi5XyVhbZ8KrxQ3q/CoqkffFTIP2hUBWhW/KHf7XVx9hxw7OOGqfQA29W9sMMwobKZ4ZhsTLq4j3FcJBqUBeyrWfb1QFEGX58x8hbKzDLFEAwKBgQCZpox7KVTDuSctfgoxEykbXNYvqysEAFYtiLap+FzYhIE/5vFVEsEjg8Esg/gZm0cpqDXSQ+UVpXNBV+jvIlMiusCcw+G2y5j/G9GXOE6317h8SJi32R/fDlsYnpqS+wWmktGvELzm8ljL9mmmZ54hLHZI+zzJgmcGu+ROia/uWwKBgQCLhlBsXns/arKbyGoQD8f5P3Do/FBJZIeQcWeIsbR+zq1f1Xi+4YrgjiGZh2MWuweKyk9MF825nPFtKlRQrkbIXwfjBjd/m0P0ooDdx+XvnykHX/Kx7msIj/T1VG4//gH/1e9ePfgKOFDMTRwd/raEAEaGiaXJ1qMn9q6vl80gdwKBgQCFa2/C2zksZAp0+QD+xrpq1a4MlseteoBLECK7DMc11gPPDl7pOW9g+SI0S/NVs29TPghNpw3mTAS3J4/svxVED6QEM+FGd+sDk22kjEPBI+FvLm/fgpOIbvkyey2X5JYiYYJAmZr9vQRewc9bXpvg64UJfoD7hEwbO6NPgQKnHQ=="
#  # 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
#  alipay_public_key : "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKPjlV8pVxHy6CjLpjYS0GUiRnS/rDXfHT67xVxbYFE+Xq/CVOJx5tNOaWvaDX6/PSWWIxoVTHkF1Rpb2WPrcfXAfOKsJ5Xf9z0oU3K0IOCAaIOnVvyiANieGNbjPHxfK46yqJjD1K4YPd+q/wlWe3BXe/2tzKYXpHX9Zzo5ap9kMvKe5FyiixB+pdhy11Ps4ii8oEperx4YVmuWQ6nhAs4yGLYsUxkTdrwEoy+2zwOCxIQuHA+9EBBJXj1pHK+GnNteNlzOOCyfmLu+MV9TadVCTwBzTTLik/jWnNtx6JgAoyiyUFyqf++hZFMYSNxWvMJpdw4B2YpF5vH/kKM/aQIDAQAB"
#  # 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数
#  notify_url : http://localhost:8082/#/AInfo
#  # 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数
#  return_url : http://localhost:8082/#/AInfo
#  # 签名方式
#  sign_type : RSA2
#  # 字符编码格式
#  charset : utf-8
#  # 支付宝网关
#  gatewayUrl : https://openapi.alipaydev.com/gateway.do
#  # 支付宝网关
#  log_path : "C:\\"
