server:
  port: 9092

#mybatis配置
mybatis:
  type-aliases-package: com.street.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




#spring配置
spring:
  application:
    name: SpringCloud-Provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.185.226:3306/talent-ecosystem?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: JX210111
    password: 123456
  servlet:
    multipart:
      # 启用
      enabled: true
      # 上传文件单个限制
      max-file-size: 5MB
      # 总限制
      max-request-size: 6MB
